news/urls.py
from django.conf.urls import url
from news import views

urlpatterns = [
	url(r'^$', views.news_list, name="news_list"),
	url(r'^(?P<pk>\d+)/destroy/$', views.post_destroy, name="post_destroy"),
]

#ajax전용 view
urlpatterns +=[
	#new_list modal
	url(r'^modal/$', views.modal, name="modal"),
	#modal 댓글 더보기
	url(r'^more/$', views.comment_more, name="comment_more"),
	#post 좋아요
	url(r'^like/$', views.news_like, name='post_like'),
	
]

tour/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import login

#static 파일
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views


#app,admin url
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^newspeed/', include('news.urls', namespace= 'news')),
    url(r'^group/', include('group.urls', namespace='group')),

]

#로그인, 로그아웃 url
urlpatterns += [
	    url(r'^$', login, name="login"),
        url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page':settings.LOGIN_URL})
]

#static url
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	title = models.CharField('제목',max_length=120)
	content = models.TextField('내용')
	tourday = models.DateField('여행날짜')
	privacy = models.ForeignKey('Postprivacy',verbose_name='Privacy related',
        related_name='%(app_label)s_%(class)ss')
	location = models.TextField('위도/경도')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	main_photo = models.ImageField('사진',upload_to='main_photo/%Y/%m/%d/')
	like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like') # post.like_set 으로 접근 가능

	def __str__(self):
		return self.title

	def delete(self, *args, **kwargs):
		self.main_photo.delete()
		for photo in self.photo_set.all():
			photo.file.delete()
			photo.delete()
		super(Post, self).delete(*args, **kwargs)

	@property
	def like_count(self):
		return self.like_user_set.count()

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Address(models.Model):
	post = models.ForeignKey('Post', verbose_name='post related',
		related_name='%(app_label)s_%(class)ss')
	address = models.TextField('주소')

class Photo(models.Model):
    post = models.ForeignKey('Post')
    file = models.ImageField('서브사진', blank=True, upload_to='sub_photo/%Y/%m/%d/')
    uploaded_at =  models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.title

class Comment(models.Model):
	post = models.ForeignKey('Post', verbose_name='post related',
		related_name='%(app_label)s_%(class)ss')
	author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=' user related',
        related_name='%(app_label)s_%(class)ss')
	message = models.TextField('댓글내용')
	created_at = models.DateTimeField('작성일',auto_now_add=True)
	updated_at =models.DateTimeField('수정일', auto_now=True)

class Postprivacy(models.Model):
    policy = models.CharField('정책',max_length=15)

    def __str__(self):
        return self.policy


class Block_user(models.Model):
    block_man = models.CharField('차단된 유저명',max_length=20)  #차단당한 유저이름
    block_man_id = models.CharField('차단된 유저ID',max_length=20)  #차단당한 유저ID
    reasons = models.CharField('차단사유',max_length=20)  #차단사유
    author = models.ForeignKey(settings.AUTH_USER_MODEL) #차단한 유저

    def __str__(self):
        return self.author.username

class Report_Post(models.Model):
    user = models.CharField('유저명',max_length=20)
    title = models.ForeignKey('Post',default = 1)
    content = models.CharField('신고내용',max_length=100)

    def __str__(self):
        return self.content

class Bookingpost(models.Model):
	from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(app_label)s_%(class)ss_from')
	to_user = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True, related_name='%(app_label)s_%(class)ss_to')
	title = models.CharField('제목',max_length=120)
	content = models.TextField('내용')
	address = models.TextField('주소')
	location = models.TextField('위도/경도')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title	        

news/forms.py
from django import forms
from .models import Comment, Block_user, Report_Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets={
        'message': forms.TextInput(attrs={
        'class':"form-control mb-2 mr-sm-2 mb-sm-0 reply_text",
        'placeholder':'댓글을 입력해주세요.',
            })
        }

class BlockForm(forms.ModelForm):
    class Meta:
        model = Block_user
        fields = ['reasons']
        widgets={
        'reasons': forms.TextInput(attrs={'class':'form-control'}),
        }

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report_Post
        fields = ['content']
        widgets={
        'content': forms.TextInput(attrs={'name':'report_content', 'class':'form-control '})
        }

news/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from .models import Post, Comment, Block_user, Report_Post
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import CommentForm, BlockForm, ReportForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import F,Q

import json

from friendship.models import Friend

@login_required
def news_list(request,
	template='news/news_list.html'):
	search = request.GET.get('search', None) #검색
	like_list = [user.post for user in request.user.like_set.all()]
	like_first = request.GET.get('like_first') #좋아요 순서
	block_form = BlockForm(request.POST) #차단 폼
	report_form = ReportForm(request.POST) #신고 폼
	report_id = request.POST.get('report_id', None) # 신고id
	post_list = Post.objects.all()

	if search:  #검색하기
		post_list = post_list.filter(title__icontains=search)

	if request.GET.get('real', None):
		template='news/news_list2.html'


	if like_first:
		post_list = Post.objects.order_by('-like')

	block = Block_user.objects.all() #차단 table객체
	blocker = block.filter(author=request.user) #차단한 유저
	post_list_real = [] #차단당하지 않은 나머지 유저들
	block_user = []	#차단당한 유저
	for i in blocker:
		block_user.append(i.block_man_id)
	for i in post_list:
		if i.author.username in block_user:
			pass
		else:
			post_list_real.append(i)

	if block_form.is_valid(): #차단하기
		block_name = request.POST.get('block_name', None) #차단당한 유저
		block_id = request.POST.get('block_id', None) #차단당한 유저
		block = block_form.save(commit=False)
		block.block_man = block_name
		block.block_man_id = block_id
		block.author = request.user
		block.save()
		return redirect('/newspeed')

	if report_form.is_valid(): #신고하기
		report_title = request.POST.get('report_title') # 신고 게시글제목
		#print(report_title)
		post = Post.objects.get(pk=report_title) #
		report = report_form.save(commit=False)
		report.user = report_id
		report.title = post
		report.save()
		return redirect('/newspeed')

	#페이지 네이션 구현 시작
	paginator = Paginator(post_list_real, 3) #3개씩 묶어 페이지 생성
	page_num = request.POST.get('page') #ajax로 page번호를 보낸다면 해당 변수에 대입

	try:
		posts= paginator.page(page_num) #해당 변수의 페이지를 posts변수에 넣어줌
	except PageNotAnInteger:
		posts= paginator.page(1) #위 상황에서 에러가 발생한다면 첫번쨰 페이지
	except EmptyPage:
		posts=paginator.page(paginator.num_page)

	if request.GET.get('real', None):
		friendlist= Friend.objects.friends(request.user) #친구 리스트
		lists=[]
		for list_object in posts:
			if list_object in friendlist:
				lists.append(list_object)
		template='news/news_list2.html'

	context = {
	'post_list':posts,
	'block_form':block_form,
	'report_form':report_form,
	'like_list':like_list,
	} #템플릿에 넘겨줄 변수

	if request.GET.get('real', None):
		lists = Post.objects.order_by('-created_at').filter(Q(author=request.user) | Q(author__friends__from_user=request.user) | Q(author__friends__to_user=request.user)).distinct()

		template='news/news_list2.html'
		context = {
		'post_list':lists,
		'block_form':block_form,
		'report_form':report_form,
		'like_list':like_list,
		} #템플릿에 넘겨줄 변수

	if request.is_ajax(): #만약 ajax로 왔을떄
		if request.POST.get('page',None): #page변수가 왔다면
			template = 'news/new_page_ajax.html' #해당 템플릿을
			return render(request, template, context) #렌더해 리턴해준다.
	#페이지 네이션 구현 끝



	return render(request, template, context)

#post모달 내용
@login_required
def modal(request, template='news/post_modal.html'):
	pk = request.POST.get('pk', None)
	post = get_object_or_404(Post, pk=pk)

	comments = Comment.objects.filter(post=post) #댓글들
	form = CommentForm(request.POST or None) #댓글 폼
	like_list = [user.post for user in request.user.like_set.all()]
	context = {'post':post,'form':form, 'comments':comments, 'like_list':like_list, }

	if request.POST.get('message', None):
		if form.is_valid():
			com= form.save(commit=False)
			com.author = request.user
			com.post = post
			com.save()
			template = 'news/comment_ajax.html'
			context = {'comment':com,}

	return render(request, template, context)

#댓글 더보기
@login_required
def comment_more(request):
	pk = request.POST.get('pk', None)
	post = get_object_or_404(Post, pk=pk)
	if request.is_ajax():
		comments = Comment.objects.filter(post=post)[4:]
		return render(request,'news/comment_more.html',{
            'comments':comments,
            })
	return redirect("news:news_list")

@login_required
def news_like(request):
    pk = request.POST.get('pk', None)
    print(pk)
    post = get_object_or_404(Post, pk=pk)
    # 중간자 모델 Like 를 사용하여, 현재 post와 request.user에 해당하는 Like 인스턴스를 가져온다.
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)

    if not post_like_created:
        post_like.delete()
        message = "like_del"
    else:
        message = "like"

    context = {'like_count': post.like_count,
               'message': message,
               'username': request.user.first_name }

    return HttpResponse(json.dumps(context))

@login_required
def post_destroy(request,pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect("/newspeed")

news/templates/news/comment_ajax.html
<tr>
	<td width="20%">{{ comment.author.get_short_name }}</td>
	<td width="50%">{{ comment.message }}</td>
	<td width="30%">{{ comment.updated_at }}</td>
</tr>    

news/templates/news/comment_more.html
{% for comment in comments %}
	<tr>
	    <td width="20%">{{ comment.author.get_short_name }}</td>
	    <td width="50%">{{ comment.message }}</td>
	    <td width="30%">{{ comment.updated_at }}</td>
	</tr>    
{% endfor %}

news/templates/news/post_modal.html
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{ post.author.first_name }} 여행자님의 게시글</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <!-- 여기부터 내용 -->
    <Main class="Main">
        <div class="container">
            <section class="posts">
                <div class="row justify-content-center">
                    <div class="col-sm-8 col-12">
                        <div class="post pl-6">
                            <p class="post_user ml-2 pt-1"><a href="#">'{{ post.author.first_name }}</a> 여행자님'</p>
                            <div class="d-flex flex-nowrap ml-2">
                                <p class="post_upload">UPLOAD DATE</p>
                                <p class="post_date ml-2 pl-1">{{post.updated_at}}</p>
                                <p class="like ml-2"><strong id="count-modal{{post.id}}">좋아요: {{post.like_set.count}}</strong></p>
                            </div>
                        </div>
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active">
                                    <a href="#" class="card-img_container d-flex justify-content-center align-items-center">
                                        <img style="height:345px;width:481px;" class="card-img-top height-fix" src="{{post.main_photo.url}}" alt="First slide">
                                    </a>
                                </div>
                                {% for photo in post.photo_set.all %}
                                <div class="carousel-item">
                                    <a href="#" class="card-img_container d-flex justify-content-center align-items-center">
                                        <img style="height:345px;width:481px;" class="card-img-top height-fix" src="{{ photo.file.url }}" alt="slide">
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="col-sm-4 col-12">
                        <div class="icon pt-3 pr-3 row justify-content-end">
                                {% if post in like_list %}
                                    <button name="{{post.id}}" href="{% url 'news:post_like' %}" type="button" class="fa fa-heart fa-2x px-2 pb-2 heart like" aria-hidden="true"></button>
                                {% else %}
                                    <button name="{{post.id}}" href="{% url 'news:post_like' %}" type="button" class="fa fa-heart-o fa-2x px-2 pb-2 heart_o like" aria-hidden="true"></button>
                                {% endif %}
                            <a href="#"><i class="fa fa-map-marker fa-2x px-1" aria-hidden="true"></i></a>
                            <div class="dropdown">
                                <button class="btn_option" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-plus fa-2x pb-2" aria-hidden="true"></i>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    {% if user.is_authenticated %}
                                        <a class="dropdown-item" href="#"><i class="fa fa-share-alt" aria-hidden="true"></i> 공유하기 </a>
                                         <a class="dropdown-item" href="/newspeed1_edit.html"><i class="fa fa-pencil" aria-hidden="true"></i> 수정하기 </a>
                                        <a class="dropdown-item" href="#"><i class="fa fa-trash-o" aria-hidden="true"></i> 삭제하기 </a>
                                    {% else %}
                                        <a class="dropdown-item" href="#"><i class="fa fa-user-times" aria-hidden="true"></i> 차단하기 </a>
                                        <div class="report" data-toggle="modal" data-target="#report">
                                            <a class="dropdown-item" href="#"><i class="fa fa-ban" aria-hidden="true"></i> 신고하기 </a>
                                        </div>
                                    {% endif %}

                                </div>

                            </div>
                        </div>
                        <p class="post_content pt-4">{{post.content}}</p>
                    </div>
                    <table class="table mt-4">
                        <tbody id = "ajax-comment">
                            {% for comment in comments|slice:":4" %}
                                <tr>
                                    <td width="20%">{{ comment.author.get_short_name }}</td>
                                    <td width="50%">{{ comment.message }}</td>
                                    <td width="30%">{{ comment.updated_at }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                        {% if comments.count > 4 %}
                            <nav aria-label="Page navigation example">
                                <input id="comment-more" type="button" name="{{post.id}}" href="{% url 'news:comment_more' %}" value="더보기">
                            </nav>
                        {% endif %}
                    <div class="container">
                        <div class="row">
                            <div class="reply">
                                {{form.message}}
                            </div>
                            <div class="reply_submit" name="{{post.id}}">
                                <button type="submit" class="btn btn-primary ajaxButton">확인</button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </Main>
</div>