accounts/urls.py
from django.conf.urls import url
from accounts import views

#index
urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^user/(?P<username>[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3})/$', views.other_map , name="other_map"),
	#tour_flag
	url(r'^tour_flag/$', views.tour_flag, name='tour_flag'),
]

#로그인 전 url
urlpatterns += [
	url(r'^joinus/$', views.joinus, name="joinus"),

]

#추억삭제
urlpatterns += [
   url(r'^delete/$', views.index_delete, name="delete"),
]

#친구
urlpatterns += [
	url(r'^friend/$', views.friend_list, name="friend_list"),
	url(r'^friend/favorites/$', views.friend_favorites, name="friend_favorites"),
	url(r'^friend/block_list/$', views.block_list, name="block_list"),
	#기능 부분
	url(r'^friend_add/(?P<pk>\d+)/$', views.friend_add , name='friend_add'),
	url(r'^friend/(?P<pk>\d+)/block_cancle/$', views.block_cancle, name="block_cancle"),
    url(r'^friend_accept/(?P<pk>\d+)/$', views.friend_accept, name="friend_accept"),
    url(r'^friend_reject/(?P<pk>\d+)/$', views.friend_reject, name="friend_reject"),
    url(r'^friend_cancel/(?P<pk>\d+)/$', views.friend_cancel, name="friend_cancel"),
    url(r'^friend_remove/(?P<pk>\d+)/$', views.friend_remove, name="friend_remove"),
]

#회원정보 수정
urlpatterns += [
	url(r'^setup_auth/$', views.setup_auth, name="setup_auth"),
	url(r'^preference/$', views.preference, name="preference"),
	url(r'^preference_design/$', views.preference_design, name="preference_design"),
	url(r'^preference_security/$', views.preference_security, name="preference_security"),
	url(r'^sign_out/(?P<pk>\d+)?/$', views.sign_out, name="sign_out"),
]

news/urls.py
from django.conf.urls import url
from news import views

urlpatterns = [
	url(r'^$', views.news_list, name="news_list"),
	url(r'^(?P<pk>\d+)/destroy/$', views.post_destroy, name="post_destroy"),
]

#ajax전용 view
urlpatterns +=[
	#new_list modal
	url(r'^modal/$', views.modal, name="modal"),
	#modal 댓글 더보기
	url(r'^more/$', views.comment_more, name="comment_more"),
	#post 좋아요
	url(r'^like/$', views.news_like, name='post_like'),
	
]

tour/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import login

#static 파일
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views


#app,admin url
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^newspeed/', include('news.urls', namespace= 'news')),
    url(r'^group/', include('group.urls', namespace='group')),

]

#로그인, 로그아웃 url
urlpatterns += [
	    url(r'^$', login, name="login"),
        url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page':settings.LOGIN_URL})
]

#static url
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	address = models.CharField('상세주소', max_length=50)
	birthdate = models.CharField('생일', max_length=120, blank=True)
	gender = models.CharField('성별', max_length=5)
	phone_num = models.CharField('전화번호', max_length=15)
	photo = models.ImageField('프로필사진', blank=True, upload_to='newspeed/%Y/%m/%d/')
	is_tour = models.BooleanField('여행여부', default=False)

	def __str__(self):
		return self.user.username

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import PostForm, Multi_PhotoForm
from news.models import Photo, Block_user
from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, get_user_model
from .models import Profile
from django.http import HttpResponse, JsonResponse
from django.db.models import F,Q
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger

#allauth
from django.contrib.auth.views import login as auth_login
from allauth.socialaccount.models import SocialApp
from allauth.socialaccount.templatetags.socialaccount import get_providers

#Form
from .forms import LoginForm,SignUpForm,CheckForm,SetupForm, BookingPostForm
#Post
from news.models import Post

import json

#사용자 인증 여부 리턴
from django.utils import timezone

#friend
from friendship.models import Friend, FriendshipRequest

@user_passes_test(lambda user : not user.is_authenticated, login_url='index')
def login(request):
	providers = []
	user = get_user_model()
	state = {}

	for provider in get_providers():
		try:
			provider.social_app = SocialApp.objects.get(provider=provider.id, sites=settings.SITE_ID)
		except SocialApp.DoesNotExist:
			provider.social_app = None
		providers.append(provider)

	if request.method == "POST":
		form = LoginForm(request, data=request.POST)
		if form.is_valid():
			auth_login(request,user)
			state['result'] = "success"
			return HttpResponse(json.dumps(state),
				content_type = "application/json")
		else:
			return render(request, 'accounts/login_modal_error.html',{
				'form':form,
				})
	else:
		form = LoginForm(request)
	return render(request, 'accounts/login.html',{
		'providers':providers, 'form':form
		})

@login_required
def index(request): #게시글 등록
	forms = Multi_PhotoForm(request.POST, request.FILES)#다중사진


	bookingform= BookingPostForm(request.user, request.POST or None)
	post_list= request.user.post_set.all().order_by('-id')
	locations= []
	if request.method == 'POST':
		if request.is_ajax():
			if bookingform.is_valid():
				bpost = bookingform.save(commit=False)
				return redirect('index')

	booking_locations = []
	bpost_list = request.user.news_bookingposts_from.all()

	for post in post_list:
		locations.append({'title':post.title, 'content':post.content,'post_id':post.id,'location':post.location})

	for bpost in bpost_list:
		booking_locations.append({'title':bpost.title, 'content':bpost.content,'post_id':bpost.id,'username':bpost.from_user.username,'location':bpost.location})

	#페이지 네이션을 위한 페이지 변수 ajax로 전달
	page = request.GET.get('page')
	try:
		page_enc = int(page)
	except TypeError:
		page_enc= 1
	#추억삭제 & Pagination 리스트를 말한다.

	search = request.GET.get('search',"")

	#검색을 했을 경우
	if request.is_ajax():
		if search:
			post_list = post_list.order_by('-id').filter(Q(title__icontains=search) | Q(tourday__icontains=search))
			paginator = Paginator(post_list, 2)

			try:
				#현재 페이지 number와 앞,뒤 페이지 정보를 가짐
				post_list = paginator.page(page)
			except PageNotAnInteger:
				#page가 integer가 아니거나 없을 경우에는 첫 번째 페이지로 이동
				post_list = paginator.page(1)
			except EmptyPage:
				#범위를 넘는 큰 수를 입력 할 경우 마지막 페이지로 이동
				post_list = paginator.page(paginator.num_pages)
			return render(request,'accounts/index_search_modal.html',{
				'post_list':post_list,
				'total_page':range(1, paginator.num_pages + 1),
				'search':search,
				'current_page':page_enc,
				})
		else:
			post_list = post_list.order_by('-id').filter(Q(title__icontains=search) | Q(tourday__icontains=search))
			paginator = Paginator(post_list, 2)

			try:
				#현재 페이지 number와 앞,뒤 페이지 정보를 가짐
				post_list = paginator.page(page)
			except PageNotAnInteger:
				#page가 integer가 아니거나 없을 경우에는 첫 번째 페이지로 이동
				post_list = paginator.page(1)
			except EmptyPage:
				#범위를 넘는 큰 수를 입력 할 경우 마지막 페이지로 이동
				post_list = paginator.page(paginator.num_pages)
			return render(request,'accounts/index_search_modal.html',{
				'post_list':post_list,
				'total_page':range(1, paginator.num_pages + 1),
				'search':search,
				'current_page':page_enc,
				})

	paginator = Paginator(post_list, 2)

	if request.method == 'POST':
		form = PostForm(request.user,request.POST,request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			if form.is_valid(): #다중사진
				files = request.FILES.getlist('file')# list형태로 입력받은 파일들을 files에 저장
				for f in files:#입력받은 리스트(사진) 순회
					Photo.objects.create(post=post, file=f)
				return redirect('index')
	elif request.method == 'GET':
		form = PostForm()

	try:
		#현재 페이지 number와 앞,뒤 페이지 정보를 가짐
		post_list = paginator.page(page)
	except PageNotAnInteger:
		#page가 integer가 아니거나 없을 경우에는 첫 번째 페이지로 이동
		post_list = paginator.page(1)
	except EmptyPage:
		#범위를 넘는 큰 수를 입력 할 경우 마지막 페이지로 이동
		post_list = paginator.page(paginator.num_pages)

	#페이지 네이션 에러 검출ㄱ
	print("캬캬캬ㅑ캬캬캬ㅑ캬ㅑ캬")


	if page:
		return render(request, 'accounts/index_search_modal.html',{
			'post_list':post_list,
			'total_page':range(1, paginator.num_pages + 1),
			'current_page':page_enc,

			})

	return render(request, 'accounts/index.html', {
		'form':form,
		'forms':forms,
		'locations':locations,
		'booking_locations':booking_locations,
		'post_list':post_list,
		'current_page':page_enc,
		'total_page':range(1, paginator.num_pages + 1),
		'bookingform':bookingform,
		})

@login_required
def index_delete(request):
   if request.is_ajax():
      pk = request.POST.getlist('pk[]',None)
      for p in pk:
         post = Post.objects.get(pk=p)
         post.delete()
      message = {"message": "success"}
      return HttpResponse(json.dumps(message), content_type="application/json")
   message = {"message":"faild"}
   return HttpResponse('clear')


@user_passes_test(lambda user : not user.is_authenticated, login_url='index')
def joinus(request):
	form = SignUpForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		if request.FILES:
			fiels = request.FILES.get('photo',None)
		form.save()
		return redirect('login')
	return render(request, 'accounts/joinus.html',{
		'form':form
		})

@login_required
def setup_auth(request):
    if request.method == "POST":
        form = CheckForm(request.user, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user_info =  authenticate(username=username, password=password)
            if user_info is not None:
            	time = timezone.now() + timezone.timedelta(seconds=200)
            	request.session['is_auth'] = json.dumps(time.strftime('%d%H%M%S'))
            	return redirect('preference')
    elif request.method == "GET":
        form = CheckForm(request.user)
    return render(request, 'accounts/preference0_reconfirm.html',{
        'form':form,
        })

@login_required
def preference(request):
	authtime = request.session.get('is_auth', None)
	if authtime is not None:
		timenow = timezone.now()
		timenow = json.dumps(timenow.strftime('%d%H%M%S'))
		if authtime < timenow:
			return redirect('setup_auth')
	if request.method == "POST":
		form = SetupForm(user=request.user, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('/')
	elif request.method == "GET":
		form = SetupForm(user=request.user, data=request.POST)
	return render(request, 'accounts/preference1_information_modification.html',{
		'form':form,
		})

@login_required
def preference_design(request):
	authtime = request.session.get('is_auth', None)
	if authtime is not None:
		timenow = timezone.now()
		timenow = json.dumps(timenow.strftime('%d%H%M%S'))
		if authtime < timenow:
			return redirect('setup_auth')
	return render(request, 'accounts/preference2_decoration.html')

@login_required
def preference_security(request):
	authtime = request.session.get('is_auth', None)
	if authtime is not None:
		timenow = timezone.now()
		timenow = json.dumps(timenow.strftime('%d%H%M%S'))
		if authtime < timenow:
			return redirect('setup_auth')
	return render(request, 'accounts/preference3_notification_&_security.html')


@login_required
def sign_out(request, pk):
	authtime = request.session.get('is_auth', None)
	if authtime is not None:
		timenow = timezone.now()
		timenow = json.dumps(timenow.strftime('%d%H%M%S'))
		if authtime < timenow:
			return redirect('setup_auth')
	if pk:
		user = request.user
		user.delete()
		return redirect('/')
	return render(request, 'accounts/preferencen4_withdrawl.html')



def friend_list(request):
	requests_uesr = Friend.objects.requests(request.user) #받은 리스트
	friendlist= Friend.objects.friends(request.user) #친구 리스트
	sent_requests = Friend.objects.sent_requests(request.user) #보낸 리스트
	search = request.GET.get('search', None) #검색
	returns = request.GET.get('returns', None) #친구목록보기
	users = Profile.objects.all()
	lists = Post.objects.order_by('-created_at').filter(Q(author=request.user) | Q(author__friends__from_user=request.user) | Q(author__friends__to_user=request.user)).distinct()
	print(type(request.user))
	user_list=[]
	for user in users:
		if not str(request.user)==str(user):
			user_list.append(user)
	if search:  #전체유저(이름) 검색하기
		user_model = get_user_model()
		search_user = user_model.objects.filter(Q(first_name__icontains=search) | Q(username__icontains=search))
		return render(request, 'friend/friend_list.html',{
					'requests_uesr':requests_uesr,
					'sent_requests':sent_requests,
					'friend_list':friendlist,
					'search_user' : search_user,
					'users_list':user_list
					})
	if returns:
		return redirect('/index/friend')


	return render(request, 'friend/friend_list.html',{
		'requests_uesr':requests_uesr,
		'sent_requests':sent_requests,
		'friend_list':friendlist,
		'users_list':user_list
		})

#친구 요청하기
@login_required
def friend_add(request,pk):
	user = get_user_model()
	if pk:
		to_user = user.objects.all().get(pk=pk)
		from_user = request.user
		Friend.objects.add_friend(from_user,to_user)
		return redirect('friend_list')


#즐겨찾기

accounts/templates/friend/block_list.html
{% extends "layout.html" %}
{% load static %}
<!--스타일 적용-->
{% block style %}
	<link rel="stylesheet" href="{% static 'friend/friend.css' %}">
{% endblock style %}

<!--내용 시작-->
{% block content %}
	<main id="main mt-5">
        <section class="container pt-5">
            <header class="friend__header row justify-content-between pt-5">
                <h1 class="friend__header__logo">Tour Friend</h1>
                <form class="friend__header__form px-2">
                    <input type="text" class="friend__header__search form-control" id="tour__search" placeholder="여행자 검색">
                </form>
                <button type="submit" class="friend__header__btn px-3 py-1">Search</button>
            </header>

            <section class="friend__body">
                <header class="friend__body__header pt-4">
                    <nav class="frined__body__nav nav">
                      <a class="nav-link all-light-gray-font" href="{% url 'friend_list' %}">친구목록</a>
                      <a class="nav-link all-light-gray-font" href="{% url 'friend_favorites' %}">즐겨찾기</a>
                      <a class="nav-link active all-light-gray-font" href="{% url '
                      block_list' %}">차단관리</a>
                    </nav>
                </header>

                <article class="friend__body__list pt-4">
                    <div class="pt-4">
                        <h2>여행자 차단 리스트</h2>
                        <article class="friend__me__request row">
                        {% for block in block_list %}
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4 pt-2 px-1">
                                <div class="card row all__friend__card mx-0">
                                  <!--<img class="card-img-top" src="/assets/img/my.jpg" alt="Card image cap">-->
                                  <div class="card-block row justify-content-center align-items-center">
                                    <div>
                                      <h4 class="card-title all-gray-font"><a href="#">{{ block.block_man }} 여행자님</a></h4>
                                      <h5 class="card-title all-gray-font"><a href="#">({{ block.block_man_id }})</a></h5>
                                        <a href="{% url 'block_cancle' block.id %}"><button class="all-red-button py-2 px-4">차단취소</a></button>
                                    </div>
                                  </div>
                                </div>
                            </div>
                          {% endfor %}

                        </article>
                    </div>
                </article>
            </section>
        </section>
    </main>
{% endblock content %}

<!--스크립트 시작-->
{% block script %}

{% endblock script %}

accounts/templates/friend/friend_favorites.html
{% extends "layout.html" %}
{% load static %}
<!--스타일 적용-->
{% block title %}
	Tour Friend
{% endblock title %}

{% block style %}
	<link rel="stylesheet" href="{% static 'friend/friend.css' %}">
{% endblock style %}

<!--내용 시작-->
{% block content %}
	<main id="main mt-5">
        <section class="container pt-5">
            <header class="friend__header row justify-content-between pt-5">
                <h1 class="friend__header__logo">Tour Friend</h1>
                <form class="friend__header__form px-2">
                    <input type="text" class="friend__header__search form-control" id="tour__search" placeholder="여행자 검색">
                </form>
                <button type="submit" class="friend__header__btn px-3 py-1">Search</button>
            </header>
            
            <section class="friend__body">
                <header class="friend__body__header pt-4">
                    <nav class="frined__body__nav nav">
                      <a class="nav-link all-light-gray-font" href="{% url 'friend_list' %}">친구목록</a>
                      <a class="nav-link active all-light-gray-font" href="{% url 'friend_favorites' %}">즐겨찾기</a>
                      <a class="nav-link all-light-gray-font" href="{% url 'block_list' %}">차단관리</a>
                    </nav>
                </header>
                
                <article class="friend__body__list pt-4">
                    <div class="pt-4">
                        <h2>즐겨찾기 리스트</h2>
                        <article class="friend__me__request row">
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4 pt-2 px-1">
                                <div class="card row all__friend__card mx-0">
                                  <img class="card-img-top" src="/assets/img/my.jpg" alt="Card image cap">
                                  <div class="card-block row justify-content-center align-items-center">
                                    <div>
                                      <h4 class="card-title all-gray-font"><a href="#">박기철 여행자님</a></h4>
                                      <button class="all-red-button py-2 px-4">즐겨찾기 취소</button>
                                    </div>
                                  </div>
                                </div>
                                
                            </div>
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4 pt-2 px-1">
                                <div class="card row all__friend__card mx-0">
                                  <img class="card-img-top" src="/assets/img/logo.PNG" alt="Card image cap">
                                  <div class="card-block row justify-content-center align-items-center">
                                    <div>
                                      <h4 class="card-title all-gray-font"><a href="#">박기철 여행자님</a></h4>
                                      <button class="all-red-button py-2 px-4">즐겨찾기 취소</button>
                                    </div>
                                  </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4 pt-2 px-1">
                                <div class="card row all__friend__card mx-0">
                                  <img class="card-img-top" src="/assets/img/logo.PNG" alt="Card image cap">
                                  <div class="card-block row justify-content-center align-items-center">
                                    <div>
                                      <h4 class="card-title all-gray-font"><a href="#">박기철 여행자님</a></h4>
                                      <button class="all-red-button py-2 px-4">즐겨찾기 취소</button>
                                    </div>
                                  </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-6 col-lg-4 pt-2 px-1">
                                <div class="card row all__friend__card mx-0">
                                  <img class="card-img-top" src="/assets/img/logo.PNG" alt="Card image cap">
                                  <div class="card-block row justify-content-center align-items-center">
                                    <div>
                                      <h4 class="card-title all-gray-font"><a href="#">박기철 여행자님</a></h4>
                                      <button class="all-red-button py-2 px-4">즐겨찾기 취소</button>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </article>
                    </div>
                </article>
            </section>
        </section>
    </main>
{% endblock content %}

accounts/templates/friend/other_map.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
	{{user.get_short_name}}님의 여행지도
{% endblock title %}

{% block style %}
	<link rel="stylesheet" href="{% static 'friend/other_map.css' %}">
  <link rel="stylesheet" href="{% static 'news/newspeed_custom.css' %}">
{% endblock style %}

{% block content %}
	<main class="main mt-5">
    <!-- 지도 -->
    <div id="map" style="width:100%;height:100vh;">
    <div class="main__content">
      <!-- 로고 -->
      <h1 class="logo ml-4 pt-3">
        <img src="/assets/img/logo3.png" style="width: 20%;"></img>
      </h1>
    </div>

  </main>
  <!-- // main -->

  <!-- 아이콘 -->
  <div class="fixed-bottom mr-4 mb-2">
    
    <div class="d-flex justify-content-end user">
        <nav class="nav">
          <!-- 여행자 상태 -->
          <a class="nav-link user_nav py-0 pl-3">여행중</a>
          <!-- 여행자 이름 -->
          <a class="nav-link user_nav py-0 pl-3">{{user_.get_short_name}} 여행자님의 지도</a>
        </nav>
        <!--<div class="px-2 user_state">여행중</div>-->
        <!--<div class="px-2 user_name">임현경 여행자님의 지도</div>-->
    </div>
    <!-- 좌측 하단 버튼 -->
    <div class="btn-group dropup d-flex justify-content-start ml-2">
      <div class="p-2">
        <!-- 1. 친구 검색 버튼 -->
        <button type="button" class="fa fa-compass icons fa-3x main__btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <!-- 친구 검색 -->
        <div class="dropdown-menu search-friend">
          <form class="form-inline ml-2 mb-3">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success search-friend-bt my-2 my-sm-0 mr-2" type="submit">Search</button>
          </form>
          <!-- 친구 검색 내 기능 -->
          <div class="btn-group" role="group" aria-label="Basic example">
            <!-- 즐겨 찾기 -->
            <button type="button" class="fa fa-star fa-2x fa-star-icon icon ml-2 mr-2"></button>
            <!-- 친구 요청 -->
            <button type="button" class="fa fa-smile-o friend-icon icon fa-2x mr-2"></button>
            <!-- TOP 10 -->
            <button type="button" class="icon-top icon">Top 10</button>
          </div>
          <!-- 검색 목록 -->
          <div class="list-group friend-list mt-3">
            <a href="#" class="list-group-item list-group-item-action"><img class="mr-3" src="assets/img/my.jpg" alt>이유림 여행자님</a>
            <a href="#" class="list-group-item list-group-item-action"><img class="mr-3" src="assets/img/my.jpg" alt>장근열 여행자님</a>
            <a href="#" class="list-group-item list-group-item-action"><img class="mr-3" src="assets/img/my.jpg" alt>박기철 여행자님</a>
            <a href="#" class="list-group-item list-group-item-action"><img class="mr-3" src="assets/img/my.jpg" alt>오제웅 여행자님</a>
          </div>
        </div>
      </div>
      <!-- 2. 공유 버튼 -->
      <button type="button" class="fa fa-share-alt icons fa-3x main__btn" data-trigger="focus" data-toggle="popover_other_share" data-placement="top">
          <span class="sr-only">Toggle Dropdown</span>
      </button>
      <!-- 공유 -->
      <div class="dropdown-menu mr-3 pl-1 hide" id="popover-share-other-content">
        <ul class="pl-0">
          <!-- 트위터 -->
          <li><a href="#" class="twitter_l fa fa-twitter-square fa-3x"></a></li>
          <!-- 페이스북 -->
          <li><a href="#" class="fa fa-facebook-square fa-3x"></a></li>
        </ul>
      </div>
      <!-- 우측 하단 버튼 -->
      <div class="ml-auto p-2">
        <!-- 1. 친구 추가 -->
          {% if user_ in friend_list %}
            <!--친구일 경우 친구 삭제-->
            <a class="fa fa-user-times icons_friend fa-3x" href="{% url 'friend_remove' user_.id %}"></a>
          {% elif user_ in sent_requests %}
            <!--요청 상태인 경우-->
            <a class="fa fa-spinner icons_friend fa-3x"></a>
          {% else %}
            <!--친구 아닌 경우-->
            <a class="fa fa-user-plus icons_friend fa-3x" href="{% url 'friend_add' user_.id %}"></a> 
          {% endif %}  
        
        <!-- 2. 즐겨 찾기 -->
        <a class="fa fa-star icons_star fa-3x" href="#"></a>
      </div>
    </div>
  </div>

  <!-- Modal content -->
   <div id="post-modal" class="modal fade bd-example-modal-lg show " tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content post-modal-content">
              <!-- Modal content-->
          </div>
      </div>
  </div>
  <!-- /Modal content -->

{% endblock content %}
  
{% block script %}
  <script>
      var userLocations = {'locations':{{locations|safe}},
        'userid':{{user_.id}},'url':"{% url 'news:modal' %}",
       };
  </script>
	<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=06220f2994a97769a8f7ba53ca9f39b8&libraries=services,clusterer"></script>
  <script type="text/javascript" src="{% static 'accounts/other_map.js' %}"></script>
{% endblock script %}